---
- name: Check if installer is already downloaded
  stat: path=/tmp/NeXposeSetup-Linux64.bin
  register: install_file_check
  tags: [ 'nexpose' ]

- name: Download nexpose installer
  get_url: url={{ nexpose_download_url }} dest=/tmp mode=0700
  when: not install_file_check.stat.exists
  tags: [ 'nexpose' ]

- name: Diasble SELinux
  selinux: state=disabled
  tags: [ 'nexpose' ]

# Look in /opt/rapid7/nexpose/.install4j/response.varfile for available variables
- name: Install nexpose
  shell: >
    /tmp/NeXposeSetup-Linux64.bin -q -overwrite
    -Vfirstname='{{ nexpose_first_name }}'
    -Vlastname='{{ nexpose_last_name }}'
    -Vcompany='{{ nexpose_company_name }}'
    -Vusername='{{ nexpose_logon_username }}'
    -Vpassword1='{{ nexpose_logon_password }}'
    -Vpassword2='{{ nexpose_logon_password }}'
    -Vsys.installationDir='{{ nexpose_install_dir }}'
    -Vsys.component.typical\$Boolean={{ nexpose_component_typical }}
    -Vsys.component.engine\$Boolean={{ nexpose_engine }}
    -VinitService\$Boolean={{ nexpose_init_service }}
    -Dinstall4j.suppressUnattendedReboot='{{ nexpose_suppress_unattended_reboot }}'
  args:
    creates: /opt/rapid7/nexpose/plugins
  no_log: True
  tags: [ 'nexpose' , 'install' ]

- name: Set Nexpose Engine port
  replace:
    backup: yes
    dest: "{{ nexpose_install_dir }}/nse/conf/nse.xml"
    regexp: 'port="\d+"'
    replace: 'port="{{ nexpose_engine_port }}"'
  when: nexpose_engine
  notify: restart nexpose
  tags: [ 'nexpose' , 'install' , 'fwconfig' ]

- name: Set Nexpose Console port
  lineinfile:
    state: present
    backrefs: yes
    backup: yes
    dest: "{{ item.dest }}"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    backup: yes
  with_items:
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/httpd.xml',
        regexp: '^(<server port\s+)= "\d+"',
        line: '\1= "{{ nexpose_console_port }}"'
      }
    - {
        dest: '{{ nexpose_install_dir }}/nsc/conf/nsc.xml',
        regexp: '^( <WebServer port=")\d+"(.*)$',
        line: '\1{{ nexpose_console_port }}\2"'
      }
  when: not nexpose_engine
  notify: restart nexpose
  tags: [ 'nexpose' , 'install' , 'fwconfig' ]

- name: Start and enable Nexpose
  service: name={{ nexpose_service_name }} enabled=yes state=started
  tags: [ 'nexpose' ]

# - name: Remove nexpose installer
#   file: /tmp/NeXposeSetup-Linux64.bin state=absent
#   tags: [ 'nexpose' ]

- name: Copy CA Certs to be added to the keystore
  copy: src={{ item.name }} dest=/etc/pki/tls/certs owner=root group=root mode=0644
  with_items: nexpose_cacerts
  when: item.state == 'present'
  tags: [ 'nexpose' , 'certs' ]

- name: Add CA Certs to key store
  java_keystore: cert=/etc/pki/tls/certs/{{ item.name }} keystore=cacerts password=changeit alias={{ item.alias }} state={{ item.state }}
  with_items: nexpose_cacerts
  tags: [ 'nexpose' , 'certs' ]

# How to see what's in the keystore
# /opt/rapid7/nexpose/_jvm*/bin/keytool -list -v -keystore /opt/rapid7/nexpose/_jvm*/lib/security/cacerts
# Default password is 'changeit'
